"""
The `mkdocs.contrib.autodoc` extension will allow you to dynamically generate API documentation from your
Python modules and classes.

### Dynamic Generation

To have the content always generate dynamically, without the use of any markdown files, you can use the
`autodoc` page command.  This will allow you to dynamically insert a python module into the page heirarchy
at runtime.

You will need to modify your `mkdocs.yml` to include something similar to:

    mkdocs_extensions:
        - mkdocs.contrib.autodoc
    pages:
        - ['api/autodoc:mkdocs', 'API', 'mkdocs']

When this syntax is invoked on load, the `mkdocs` module will be loaded and all of its pages dynamically generated
and added to the server.  This option is nice because you will always get your latest documentation, however, if
you use this remotely you will need to confugre a virtualenv that can load your package.

### Markdown Generate

The second option is to statically build your API documentation as Markdown files that can be loaded anywhere.
This exists as a command-line extension to the `mkdocs` commands, and works similarly, execpt instead of generating
dynamic HTML content, it will export out *.md files to your documents root.  This method will also require
use of the [mkdocs.contrib.tree](/api/mkdocs/contrib/tree/) extension.

You will need to call this whenever you want to re-generate your API documentation, however it will not need access
to your code libraries on remote servers.

You will need to modify your `mkdocs.yml` file to include something simliar to:

    mkdocs_extensions:
        - mkdocs.contrib.tree
        - mkdocs.contrib.autodoc
    pages:
        - ['tree:api/mkdocs', 'API', 'mkdocs']

To use this, you will need to invoke the command from the command line:

    $> mkdocs autodoc-generate mkdocs

You can specify `--outpath=/path/to/output` which will default to `docs/api` as well as `--basepath=/path/to/base`
which will be the page's base path (defaulting to `api`).

__WARNING: This will *remove* the `outpath` before building, so you should always only keep autogenerated docs in it.__
"""

from mkdocs import events

from .nav import load_module
from . import build, config as ext_config

def main(event):
    if event.cmd == 'autodoc-generate':
        modules = [arg for arg in event.args if not arg.startswith('--')]
        base_path = event.options.get('basepath', 'api')
        out_path = event.options.get('outpath', './docs/api')

        for module_name in modules:
            page = load_module(module_name, base_path)
            page.export_markdown(out_path)

        return True
    else:
        return False

def includeme(config):
    """
    Initializes the extension for the mkdocs system.

    ### Parameters
        config | <dict>
    """
    # update the configuration options
    ext_config.update(config.get('autodoc_options', {}))
    ext_config.base_config = config

    # register callback options
    events.register_callback(events.BuildPage, build.create_api_page)
    events.register_callback(events.GenerateContent, build.create_api_content)
    events.register_callback(events.Execute, main)

    # register the additional command line option
    events.Execute.commands.add('autodoc-generate')