#!/usr/bin/env python
#coding: utf-8

import mkdocs
import shutil
import sys
import tempfile


def arg_to_option(arg):
    """
    Convert command line arguments into two-tuples of config key/value pairs.
    """
    arg = arg.lstrip('--').replace('-', '_')
    if '=' in arg:
        return arg.split('=', 1)
    return (arg, True)


def main(options=None):
    """
    Build the documentation, and optionally start the devserver.
    """
    if 'serve' in options:
        tempdir = tempfile.mkdtemp()
        options['build_dir'] = tempdir

    config = mkdocs.load_config(options=options)
    mkdocs.build(config)

    if 'serve' in options:
        mkdocs.serve(config, options=options)
        shutil.rmtree(tempdir)


if __name__ == '__main__':
    args = [arg_to_option(arg) for arg in sys.argv[1:] if arg.startswith('--')]
    main(options=dict(args))
